//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loadingStation.Base.Configuration.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Modbusconfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static Modbusconfig defaultInstance = ((Modbusconfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Modbusconfig())));
        
        public static Modbusconfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ModbusDebugInput {
            get {
                return ((string)(this["ModbusDebugInput"]));
            }
            set {
                this["ModbusDebugInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ModbusDebugOutput {
            get {
                return ((string)(this["ModbusDebugOutput"]));
            }
            set {
                this["ModbusDebugOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public int ModbusDebugInputPort {
            get {
                return ((int)(this["ModbusDebugInputPort"]));
            }
            set {
                this["ModbusDebugInputPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public int ModbusDebugOutputPort {
            get {
                return ((int)(this["ModbusDebugOutputPort"]));
            }
            set {
                this["ModbusDebugOutputPort"] = value;
            }
        }
    }
}
